#!/bin/bash


DOCKER_IMAGE_NAME=sawtooth-smartcontract
DOCKER_FULL_IMAGE_NAME=ghcr.io/jffp113/${DOCKER_IMAGE_NAME}:latest

docker build -t $DOCKER_FULL_IMAGE_NAME -f ./examples/intkey_go/Dockerfile-installed-bionic .